### ISSUE TITLE
readme.md pip install command incorrect

### ISSUE THREAD

**Issue by aaron-schnieder** [Azure/azure-cosmosdb-python#10]
Readme.md for azure-cosmosdb-table pip install command is incorrect, it is still listed as:
```
pip install azure-storage-table
```
Which no longer exists. 

Should be: 
```
pip install azure-cosmosdb-table
```

**Comment by kygx-legend** [comment]
Please correct that!

By the way, the official document [table-storage-how-to-use-python](https://docs.microsoft.com/en-us/azure/cosmos-db/table-storage-how-to-use-python) should be updated too.

**Comment by srinathnarayanan** [comment]
Hi @aaron-schnieder . We have corrected it.

**Comment by srinathnarayanan** [comment]
Closing this issue. Feel free to reopen it if you find anything else. Thanks!
