### ISSUE TITLE
Documentation links to deprecation notice / Can this be used with traditional AzureTables?

### ISSUE THREAD

**Issue by arshbucks** [Azure/azure-cosmosdb-python#17]
I'm trying to use traditional AzureTables (no CosmosDB).

The ReadMe for azure-cosmosdb-table in this repo
https://github.com/Azure/azure-cosmosdb-python/tree/master/azure-cosmosdb-table
links back to an article that says it is deprecated.
https://docs.microsoft.com/en-us/azure/cosmos-db/table-storage-how-to-use-python

As of right now, can the code/info in the article above ("how to use python") be used **as is for the forseeable future (or has it begun the 12mo deprecation cycle?** (and can we trust that the **azure-cosmos-table pip package** will remain stable/updated through this repo? )

Or will it change/become unusable in the near future, so only CosmosDB (and not traditional AzureTables) is supported?

Thanks for any insight you can provide.

**Comment by ausfeldt** [comment]
The azure-cosmos-table pip package will updated in this repo and will be backward compatible with the traditional Azure Table Storage for the foreseeable future.
