### ISSUE TITLE
azure-cosmosdb-table 1.0.3 has requirement azure-storage-common<1.2.0,>=1.1.0, but you'll have azure-storage-common 1.2.0rc1 which is incompatible.

### ISSUE THREAD

**Issue by smdsaleem** [Azure/azure-cosmosdb-python#26]
azure-cosmosdb-table 1.0.3 has requirement azure-storage-common<1.2.0,>=1.1.0, but you'll have azure-storage-common 1.2.0rc1 which is incompatible.

**Comment by naumvd95** [comment]
azure-cosmosdb-table 1.0.3 has requirement azure-storage-common<1.2.0,>=1.1.0, but you have azure-storage-common 1.3.0.

**Comment by lmazuel** [comment]
FYI fix is merged, waiting for release:
https://github.com/Azure/azure-cosmosdb-python/pull/29

**Comment by srinathnarayanan** [comment]
V 1.0.5 has been released and has this change.
