### ISSUE TITLE
Please drop dependency on azure-storage-common

### ISSUE THREAD

**Issue by zezha-msft** [Azure/azure-cosmosdb-python#39]
There's been numerous issues related to the dependency version binding: 

1. https://github.com/Azure/azure-cosmos-table-python/issues/28
2. https://github.com/Azure/azure-cosmos-table-python/issues/15
3. https://github.com/Azure/azure-cosmos-table-python/issues/19
4. https://github.com/Azure/azure-cosmos-table-python/issues/26

And most recently this [one](https://github.com/Azure/azure-storage-python/issues/613).

We increment the version of the common package quite often, and the changes almost never impact the table package. It'd better if the table package keeps its own copy of the common files (like before), rather than having a direct dependency, which keeps causing issues for the users.

**Comment by stefangordon** [comment]
Seems like this should be escalated immediately.   At the moment there isn't a working storage SDK story.  P0.

**Comment by alfpark** [comment]
@srinathnarayanan, is anyone looking into this issue? This package is broken against current Python Storage packages.

**Comment by Kagigz** [comment]
Any news on this?

**Comment by brsmyth** [comment]
Which is the right team to look at this? It creates some very restrictive pinned requirements when requiring `azure-cosmosdb-table`.

**Comment by jondavidi** [comment]
@zezha-msft Any updates on this? This issue has been open for awhile now and as others have said is causing a restrictive and constraining requirements environment.

**Comment by Kagigz** [comment]
@zezha-msft can we please reopen this issue? Apparently it's still not possible to use the Azure Storage Python SDK and the cosmosdb-table package in the same project due to dependencies.

**Comment by zezha-msft** [comment]
Hi @Kagigz this issue was never closed, what do you mean?

FYI @srinathnarayanan is working on solving it.

**Comment by Kagigz** [comment]
@zezha-msft sorry it was the linked issue (plugin dependency validation fix) that was closed, my bad!

**Comment by srinathnarayanan** [comment]
Latest version of azure-cosmos-tables (V1.0.6) removes dependency on azure-storage-common. https://pypi.org/project/azure-cosmosdb-table/1.0.6/
