### ISSUE TITLE
azure-cosmosdb-tables does not support CosmosDB Tables Service

### ISSUE THREAD

**Issue by clayhagler** [Azure/azure-cosmosdb-python#9]
This is a case of a unfortunately named library that may lead you to believe you could use it to connect to the CosmosDB Table API. 

Do not be misled by the links on the CosmosDB Table API page: https://docs.microsoft.com/en-us/azure/cosmos-db/table-introduction 

A rename of the project is certainly in order.

I hope that a future version will support the new API soon.

Thank you to @srinathnarayanan for confirming this with me.

**Comment by srinathnarayanan** [comment]
With patch 1.0.1, You can now use the azure-cosmosdb-table sdk to connect to the CosmosDB Table API using the connection string provided for your table api on the portal. Please check out the fix and feel free to close the issue.

**Comment by clayhagler** [comment]
Thank you. I will.
-Clay

**Comment by srinathnarayanan** [comment]
I am closing this issue as it has been addressed. Feel free to reopen it if you are running into a similar issue. Thanks!
